### ISSUE TITLE
Designate output directory for L2A_Process command-line 

### ISSUE THREAD

**Issue by Woodstonelee** [umwilm/SEN2COR#5]
Hi when I use L2A_Process on Linux in command line, I found no option to designate the output directory. The output folder name of the L2A data is automatically generated in the same place as the input L1C data. Now we try to process a lot of data on our server but want to separate the original downloaded L1C and L2A. And sometimes some people on our serve does not have write access to the L1C data folder. Can we add an option to the L2A_Process to designate the output directory?

Or is there already one? And How?

**Comment by umwilm** [comment]
This is a configurable option inside of the L2A_GIPP.xml configuration file. It is described in the User manual at section 3.2.1. The user manual can be downloaded at the same location where the processor is located.

**Comment by Woodstonelee** [comment]
@umwilm thanks a lot for the help! This will work for me now. But I'm wondering if it's better if you can also choose the output directory at the time of running the command to add a bit more flexibility.
